# Site settings
title: AAKASH TUTEJA
email: tutejaaakash4@gmail.com
description: Data Scientist # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aakashtuteja4.github.io" # the base hostname & protocol for your site

linkedin_username: aakash-tuteja-015394187
twitter_username: 
github_username: aakashtuteja4

# Build settings
markdown: kramdown
